title: Галерея Индексмод
email: indexmod@me.com
description: >- # this means to ignore newlines until "baseurl:"
  "Это экспериментальная онлайн галерея где можно увидеть как создавалась работа".
baseurl: "" # the subpath of your site, e.g. /blog
url: "gallery.indexmod.xyz" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: indexmod
github_username:  indexmod

exclude: []
